### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by SamCastello** [xlanex6/dreamstones#3]
Dans cet ordre plutôt. On s'est mal compris désolé...

![screen shot 2016-11-14 at 17 44 43](https://cloud.githubusercontent.com/assets/23459511/20275959/5040d664-aa92-11e6-87d8-f5775ea7bd99.png)
![screen shot 2016-11-14 at 17 44 58](https://cloud.githubusercontent.com/assets/23459511/20275966/56c96280-aa92-11e6-8c46-6ac07c19a7be.png)
![screen shot 2016-11-14 at 17 45 22](https://cloud.githubusercontent.com/assets/23459511/20275975/5a00300a-aa92-11e6-9e33-93625a533a34.png)
![screen shot 2016-11-14 at 17 45 12](https://cloud.githubusercontent.com/assets/23459511/20275980/5e31a53c-aa92-11e6-8f5d-8b5360bfd68b.png)
![screen shot 2016-11-14 at 17 45 29](https://cloud.githubusercontent.com/assets/23459511/20275984/61d5a6de-aa92-11e6-836e-a179a58c2223.png)

**Comment by xlanex6** [comment]
DONE

**Comment by SamCastello** [comment]
belle!

**Comment by xlanex6** [comment]
mais il faut poncer les ecarts

**Comment by SamCastello** [comment]
Fait Peter le DREAMSTONES en gros sans "The futur of" =)

![screen shot 2016-11-14 at 17 44 43](https://cloud.githubusercontent.com/assets/23459511/20276251/6bd7aa78-aa93-11e6-9d08-b7c2e18f71d3.png)
